#include <efi.h>
#include <efi/libsmbios.h>
#include <video.h>
#include <csmwrap.h>
#include <oprom.h>
#include <config.h>
#include <io.h>

// Generated by: xxd -i vgabios.bin >> vgabios.h
#include <bins/vgabios.h>

void *vbios_loc = NULL;
uintptr_t vbios_size;

/*
 * Calculate bits per pixel from linear pixel masks.
 * Ported from Limine.
 */
static uint16_t linear_masks_to_bpp(uint32_t red_mask, uint32_t green_mask,
                                    uint32_t blue_mask, uint32_t alpha_mask)
{
    uint32_t compound_mask = red_mask | green_mask | blue_mask | alpha_mask;
    uint16_t ret = 32;
    while ((compound_mask & (1 << 31)) == 0) {
        ret--;
        compound_mask <<= 1;
    }
    return ret;
}

/*
 * Find a GOP with a valid framebuffer and set its mode.
 * This is needed for Flanterm and SeaVGABIOS framebuffer access.
 */
static EFI_STATUS FindGop(struct csmwrap_priv *priv)
{
    EFI_STATUS Status;
    EFI_HANDLE *HandleBuffer;
    UINTN HandleCount;
    EFI_GUID gopGuid = EFI_GRAPHICS_OUTPUT_PROTOCOL_GUID;
    EFI_GRAPHICS_OUTPUT_PROTOCOL *Gop;

    Status = gBS->LocateHandleBuffer(
                    ByProtocol,
                    &gopGuid,
                    NULL,
                    &HandleCount,
                    &HandleBuffer
                    );
    if (EFI_ERROR(Status)) {
        printf("Failed to locate GOP handles: %d\n", Status);
        return Status;
    }

    // Iterate through each GOP handle, find one with valid FrameBufferBase
    for (UINTN i = 0; i < HandleCount; i++) {
        Status = gBS->HandleProtocol(
                        HandleBuffer[i],
                        &gopGuid,
                        (VOID**)&Gop
                        );
        if (EFI_ERROR(Status)) {
            continue;
        }

        // Initialize GOP if not started
        UINTN currentMode = Gop->Mode == NULL ? 0 : Gop->Mode->Mode;
        EFI_GRAPHICS_OUTPUT_MODE_INFORMATION *modeInfo;
        UINTN modeInfoSize;

        Status = Gop->QueryMode(Gop, currentMode, &modeInfoSize, &modeInfo);
        if (Status == EFI_NOT_STARTED) {
            Status = Gop->SetMode(Gop, 0);
            if (EFI_ERROR(Status)) {
                continue;
            }
        }

        // Try all modes to find one with valid FrameBufferBase
        UINTN maxMode = Gop->Mode->MaxMode;
        bool found = false;
        for (UINTN mode = 0; mode < maxMode; mode++) {
            Status = Gop->SetMode(Gop, mode);
            if (EFI_ERROR(Status)) {
                continue;
            }

            if (Gop->Mode->FrameBufferBase == 0) {
                continue;
            }

            EFI_GRAPHICS_OUTPUT_MODE_INFORMATION *mi = Gop->Mode->Info;

            /* Skip PixelBltOnly and unknown pixel formats */
            if (mi->PixelFormat >= PixelBltOnly) {
                continue;
            }

            /* Reject PixelBitMask modes with all-zero masks */
            if (mi->PixelFormat == PixelBitMask
             && (mi->PixelInformation.RedMask
               | mi->PixelInformation.GreenMask
               | mi->PixelInformation.BlueMask
               | mi->PixelInformation.ReservedMask) == 0) {
                continue;
            }

            /* Validate pitch: PixelsPerScanLine must be >= HorizontalResolution */
            if (mi->PixelsPerScanLine < mi->HorizontalResolution) {
                continue;
            }

            found = true;
            break;
        }

        if (!found) {
            continue;
        }

        priv->gop = Gop;
        priv->gop_handle = HandleBuffer[i];
        break;
    }

    gBS->FreePool(HandleBuffer);

    if (priv->gop == NULL) {
        printf("No GOP with valid framebuffer found\n");
        return EFI_NOT_FOUND;
    }

    return EFI_SUCCESS;
}

/*
 * Populate priv VGA PCI fields from a PCI I/O protocol handle.
 */
static void PopulateVgaPciInfo(struct csmwrap_priv *priv, EFI_PCI_IO_PROTOCOL *PciIo)
{
    UINT16 VendorId, DeviceId;
    UINTN Seg, Bus, Device, Function;

    priv->vga_pci_io = PciIo;

    PciIo->GetLocation(PciIo, &Seg, &Bus, &Device, &Function);

    priv->vga_pci_bus = (UINT8)Bus;
    priv->vga_pci_devfn = (UINT8)(Device << 3 | Function);

    PciIo->Pci.Read(PciIo, EfiPciIoWidthUint16, 0, 1, &VendorId);
    PciIo->Pci.Read(PciIo, EfiPciIoWidthUint16, 2, 1, &DeviceId);

    priv->vga_vendor_id = VendorId;
    priv->vga_device_id = DeviceId;

    printf("VGA PCI: %04x:%02x:%02x.%x %04x:%04x\n",
                Seg, (UINT8)Bus, (UINT8)Device, (UINT8)Function,
                VendorId, DeviceId);
}

/*
 * Find a PCI device by bus/device/function and return its PCI I/O protocol.
 */
static EFI_STATUS FindPciDevice(uint8_t bus, uint8_t device, uint8_t function,
                                 EFI_PCI_IO_PROTOCOL **OutPciIo)
{
    EFI_STATUS Status;
    EFI_HANDLE *HandleBuffer;
    UINTN HandleCount;
    EFI_GUID PciIoGuid = EFI_PCI_IO_PROTOCOL_GUID;

    Status = gBS->LocateHandleBuffer(ByProtocol, &PciIoGuid, NULL,
                                      &HandleCount, &HandleBuffer);
    if (EFI_ERROR(Status))
        return Status;

    for (UINTN i = 0; i < HandleCount; i++) {
        EFI_PCI_IO_PROTOCOL *PciIo;
        Status = gBS->HandleProtocol(HandleBuffer[i], &PciIoGuid, (VOID **)&PciIo);
        if (EFI_ERROR(Status))
            continue;

        UINTN Seg, Bus, Device, Function;
        PciIo->GetLocation(PciIo, &Seg, &Bus, &Device, &Function);

        if ((uint8_t)Bus == bus &&
            (uint8_t)Device == device &&
            (uint8_t)Function == function) {
            *OutPciIo = PciIo;
            gBS->FreePool(HandleBuffer);
            return EFI_SUCCESS;
        }
    }

    gBS->FreePool(HandleBuffer);
    return EFI_NOT_FOUND;
}

/*
 * Find PCI device info for VGA output.
 *
 * If a specific VGA device is configured, locate it by PCI address.
 * Otherwise, derive it from the GOP handle's device path.
 *
 * This is needed for OpROM loading, VGA arbitration, and legacy handoff.
 */
static EFI_STATUS FindVgaPciInfo(struct csmwrap_priv *priv)
{
    EFI_STATUS Status;
    EFI_PCI_IO_PROTOCOL *PciIo;

    /* If user specified a VGA device, find it directly by PCI address */
    if (gConfig.vga_specified) {
        Status = FindPciDevice(gConfig.vga_bus, gConfig.vga_device,
                                gConfig.vga_function, &PciIo);
        if (EFI_ERROR(Status)) {
            printf("VGA: configured device %02x:%02x.%x not found\n",
                   gConfig.vga_bus, gConfig.vga_device, gConfig.vga_function);
            return Status;
        }

        PopulateVgaPciInfo(priv, PciIo);
        return EFI_SUCCESS;
    }

    /* Default: derive from GOP handle's device path */
    EFI_GUID DevicePathGuid = EFI_DEVICE_PATH_PROTOCOL_GUID;
    EFI_GUID PciIoGuid = EFI_PCI_IO_PROTOCOL_GUID;
    EFI_DEVICE_PATH_PROTOCOL *DevicePath;
    EFI_HANDLE Handle;

    if (priv->gop_handle == NULL)
        return EFI_NOT_FOUND;

    Status = gBS->HandleProtocol(priv->gop_handle, &DevicePathGuid,
                                  (VOID **)&DevicePath);
    if (EFI_ERROR(Status))
        return Status;

    Status = gBS->LocateDevicePath(&PciIoGuid, &DevicePath, &Handle);
    if (EFI_ERROR(Status))
        return Status;

    Status = gBS->HandleProtocol(Handle, &PciIoGuid, (VOID **)&PciIo);
    if (EFI_ERROR(Status))
        return Status;

    PopulateVgaPciInfo(priv, PciIo);
    return EFI_SUCCESS;
}

static EFI_STATUS csmwrap_pci_vgaarb(struct csmwrap_priv *priv)
{
    EFI_STATUS Status;
    EFI_PCI_IO_PROTOCOL *PciIo = priv->vga_pci_io;
    UINT64 Attributes = 0;
    UINT64 Supported = 0;
    BOOLEAN unsupported = FALSE;

    if (!PciIo) {
        return -1;
    }

    Status = PciIo->Attributes(PciIo, EfiPciIoAttributeOperationSupported,
                               0, &Supported);

    if (EFI_ERROR(Status)) {
        printf("%s: Failed to get supported attributes: %d\n", __func__, Status);
        return Status;
    }

    Attributes = Supported & (EFI_PCI_IO_ATTRIBUTE_VGA_IO | EFI_PCI_IO_ATTRIBUTE_VGA_IO_16);

    if (Attributes == 0) {
        printf("%s: No VGA IO attributes support\n", __func__);
        unsupported = TRUE;
    } else if (Attributes == (EFI_PCI_IO_ATTRIBUTE_VGA_IO | EFI_PCI_IO_ATTRIBUTE_VGA_IO_16)) {
        Attributes = EFI_PCI_IO_ATTRIBUTE_VGA_IO; // We want to use regular VGA IO
    }

    if (Supported & EFI_PCI_IO_ATTRIBUTE_VGA_MEMORY) {
        Attributes |= EFI_PCI_IO_ATTRIBUTE_VGA_MEMORY;
    } else {
        printf("%s: No VGA memory attributes support\n", __func__);
        unsupported = TRUE;
    }

    if (unsupported) {
        printf("%s: Unable to select attribute\n", __func__);
        return -1;
    }

    Status = PciIo->Attributes(PciIo, EfiPciIoAttributeOperationEnable,
                               Attributes, NULL);
    if (EFI_ERROR(Status)) {
        printf("%s: Failed to set attributes: %d\n", __func__, Status);
        return Status;
    }

    printf("%s: Success! Attributes: %llx\n", __func__, Attributes);

    return 0;
}

/*
 * Check SMBIOS type 3 (System Enclosure) to determine if this is a portable.
 */
static bool is_portable_chassis(void)
{
    EFI_GUID smbiosGuid = SMBIOS_TABLE_GUID;
    EFI_GUID smbios3Guid = SMBIOS3_TABLE_GUID;
    const uint8_t *table = NULL;
    uint32_t table_size = 0;

    /* Find SMBIOS structure table address and size */
    for (UINTN i = 0; i < gST->NumberOfTableEntries; i++) {
        EFI_CONFIGURATION_TABLE *entry = &gST->ConfigurationTable[i];
        if (!efi_guidcmp(entry->VendorGuid, smbiosGuid)) {
            SMBIOS_TABLE_ENTRY_POINT *ep = entry->VendorTable;
            table = (const uint8_t *)(uintptr_t)ep->TableAddress;
            table_size = ep->TableLength;
            break;
        }
        if (!efi_guidcmp(entry->VendorGuid, smbios3Guid)) {
            SMBIOS_TABLE_3_0_ENTRY_POINT *ep = entry->VendorTable;
            table = (const uint8_t *)(uintptr_t)ep->TableAddress;
            table_size = ep->TableMaximumSize;
            /* Don't break — prefer 2.x if both exist */
        }
    }

    if (!table || table_size == 0)
        return false;

    /* Walk structures looking for type 3 */
    const uint8_t *ptr = table;
    const uint8_t *end = table + table_size;

    while (ptr + sizeof(SMBIOS_HEADER) <= end) {
        const SMBIOS_HEADER *hdr = (const SMBIOS_HEADER *)ptr;

        if (hdr->Length < sizeof(SMBIOS_HEADER))
            break;
        if (ptr + hdr->Length > end)
            break;

        if (hdr->Type == 3 && hdr->Length >= 5) {
            /* Chassis type is byte at offset 5 (after 4-byte header) */
            uint8_t chassis_type = ptr[5] & 0x7F; /* Mask out lock bit */
            switch (chassis_type) {
            case 8:  /* Portable */
            case 9:  /* Laptop */
            case 10: /* Notebook */
            case 14: /* Sub Notebook */
            case 31: /* Convertible */
            case 32: /* Detachable */
                return true;
            }
            return false;
        }

        /* Skip past formatted area and string section (double-null terminated) */
        const uint8_t *str = ptr + hdr->Length;
        while (str + 1 < end) {
            if (str[0] == 0 && str[1] == 0) {
                str += 2;
                break;
            }
            str++;
        }

        if (hdr->Type == 127)
            break;

        ptr = str;
    }

    return false;
}

/*
 * Check if the system has more than one PCI display-class device.
 */
static bool has_multiple_gpus(void)
{
    EFI_STATUS Status;
    EFI_HANDLE *HandleBuffer;
    UINTN HandleCount;
    EFI_GUID PciIoGuid = EFI_PCI_IO_PROTOCOL_GUID;
    UINTN gpu_count = 0;

    Status = gBS->LocateHandleBuffer(ByProtocol, &PciIoGuid, NULL,
                                      &HandleCount, &HandleBuffer);
    if (EFI_ERROR(Status))
        return false;

    for (UINTN i = 0; i < HandleCount; i++) {
        EFI_PCI_IO_PROTOCOL *PciIo;
        PCI_TYPE00 PciConfig;

        Status = gBS->HandleProtocol(HandleBuffer[i], &PciIoGuid, (VOID **)&PciIo);
        if (EFI_ERROR(Status))
            continue;

        Status = PciIo->Pci.Read(PciIo, EfiPciIoWidthUint32, 0,
                                  sizeof(PciConfig) / sizeof(UINT32), &PciConfig);
        if (EFI_ERROR(Status))
            continue;

        if (PciConfig.Hdr.ClassCode[2] == PCI_CLASS_DISPLAY)
            gpu_count++;
    }

    gBS->FreePool(HandleBuffer);
    return gpu_count > 1;
}

/*
 * Detect dual-GPU laptop configurations where OpROM dispatch is unsafe.
 * Returns true if the system is a portable with multiple GPUs (iGPU + dGPU),
 * indicating a MUX switch, Optimus, or dGPU-direct display topology.
 */
static bool is_dual_gpu_laptop(void)
{
    if (!is_portable_chassis())
        return false;
    return has_multiple_gpus();
}

static EFI_STATUS csmwrap_video_oprom_init(struct csmwrap_priv *priv)
{
    EFI_STATUS Status;
    PCI_TYPE00 PciConfigHeader;
    EFI_PCI_IO_PROTOCOL *PciIo;
    UINTN  LocalRomSize;
    VOID  *LocalRomImage;

    /* Find PCI device info - required for OpROM */
    FindVgaPciInfo(priv);

    PciIo = priv->vga_pci_io;
    if (!PciIo || !PciIo->RomImage || !PciIo->RomSize) {
        return EFI_UNSUPPORTED;
    }

    /*
     * On dual-GPU laptops (iGPU + dGPU), the display may be physically
     * routed to the dGPU via a MUX switch or hardwired connection.
     * The iGPU's OpROM will hang waiting for a display that isn't there.
     * VGA arbitration alone doesn't catch MUX-switched configs since PCI
     * decode can succeed even when the panel is routed elsewhere.
     *
     * Skip this check if the user explicitly selected a GPU with vga= —
     * they know which device has a working display path.
     */
    if (is_dual_gpu_laptop()) {
        printf("Dual-GPU laptop detected, skipping OpROM for %04x:%04x\n",
               priv->vga_vendor_id, priv->vga_device_id);
        return EFI_UNSUPPORTED;
    }

    /*
     * Enable VGA routing to this device for legacy OpROM execution.
     * On dual-GPU laptops (MUX switch, dGPU-direct, or Optimus), VGA I/O
     * and memory may be routed to the discrete GPU. If we can't claim VGA
     * resources for this device, the OpROM will try to talk to hardware
     * that isn't listening, causing a hang.
     */
    Status = csmwrap_pci_vgaarb(priv);
    if (Status != EFI_SUCCESS) {
        printf("VGA arbitration failed for %04x:%04x, skipping OpROM\n",
               priv->vga_vendor_id, priv->vga_device_id);
        return EFI_UNSUPPORTED;
    }

    LocalRomSize  = (UINTN) PciIo->RomSize;
    LocalRomImage = PciIo->RomImage;

    PciIo->Pci.Read (
            PciIo,
            EfiPciIoWidthUint32,
            0,
            sizeof (PciConfigHeader) / sizeof (UINT32),
            &PciConfigHeader
            );

    Status = GetPciLegacyRom (
             0x0300, // ???
             PciConfigHeader.Hdr.VendorId,
             PciConfigHeader.Hdr.DeviceId,
             &LocalRomImage,
             &LocalRomSize,
             NULL /* RuntimeImageLength */,
             NULL /* OpromRevision */,
             NULL /* &LocalConfigUtilityCodeHeader */
             );

    if (EFI_ERROR(Status)) {
        DEBUG((DEBUG_ERROR, "GetPciLegacyRom failed: %r\n", Status));
        return Status;
    }

    /* Reject OpROM if it won't fit below the CSM binary */
    uintptr_t max_vbios_size = priv->csm_bin_base - VGABIOS_START;
    if (LocalRomSize > max_vbios_size) {
        printf("OpROM too large (%u bytes, max %u), skipping\n",
               (unsigned)LocalRomSize, (unsigned)max_vbios_size);
        return EFI_UNSUPPORTED;
    }

    vbios_loc = LocalRomImage;
    vbios_size = LocalRomSize;

    priv->video_type = CSMWRAP_VIDEO_OPROM;

    printf("Video Initialisation Succeed with OpROM\n");

    return 0;
}

static EFI_STATUS csmwrap_video_seavgabios_init(struct csmwrap_priv *priv)
{
    struct cb_framebuffer *cb_fb = &priv->cb_fb;
    unsigned long fb_addr = 0;
    EFI_STATUS status;
    EFI_GRAPHICS_OUTPUT_PROTOCOL *gop = priv->gop;
    EFI_GRAPHICS_OUTPUT_MODE_INFORMATION *info = NULL;
    UINTN isiz = sizeof(EFI_GRAPHICS_OUTPUT_MODE_INFORMATION), currentMode;

    if (!gop) {
        return EFI_UNSUPPORTED;
    }

    /* Mode already set by FindGopPciDevice, just query info */
    currentMode = gop->Mode->Mode;
    status = gop->QueryMode(gop, currentMode, &isiz, &info);
    if (EFI_ERROR(status)) {
        printf("unable to get current video mode\n");
        return -1;
    }

    printf("%c %3d. %4d x%4d (pitch %4d fmt %d r:%06x g:%06x b:%06x)\n",
        '*', currentMode,
        info->HorizontalResolution, info->VerticalResolution, info->PixelsPerScanLine, info->PixelFormat,
        info->PixelFormat==PixelRedGreenBlueReserved8BitPerColor?0xff:(
        info->PixelFormat==PixelBlueGreenRedReserved8BitPerColor?0xff0000:(
        info->PixelFormat==PixelBitMask?info->PixelInformation.RedMask:0)),
        info->PixelFormat==PixelRedGreenBlueReserved8BitPerColor ||
        info->PixelFormat==PixelBlueGreenRedReserved8BitPerColor?0xff00:(
        info->PixelFormat==PixelBitMask?info->PixelInformation.GreenMask:0),
        info->PixelFormat==PixelRedGreenBlueReserved8BitPerColor?0xff0000:(
        info->PixelFormat==PixelBlueGreenRedReserved8BitPerColor?0xff:(
        info->PixelFormat==PixelBitMask?info->PixelInformation.BlueMask:0)));

    fb_addr = (unsigned long)gop->Mode->FrameBufferBase;

    printf("EFI Framebuffer: %lx\n", fb_addr);

    if (!fb_addr) {
        printf("Framebuffer invalid.\n");
        return EFI_UNSUPPORTED;
    }

    cb_fb->physical_address = fb_addr;
    cb_fb->x_resolution = info->HorizontalResolution;
    cb_fb->y_resolution = info->VerticalResolution;

    switch (info->PixelFormat) {
        case PixelRedGreenBlueReserved8BitPerColor:
            cb_fb->bits_per_pixel = 32;
            cb_fb->red_mask_pos = 0;
            cb_fb->red_mask_size = 8;
            cb_fb->green_mask_pos = 8;
            cb_fb->green_mask_size = 8;
            cb_fb->blue_mask_pos = 16;
            cb_fb->blue_mask_size = 8;
            cb_fb->reserved_mask_pos = 24;
            cb_fb->reserved_mask_size = 8;
            break;
        case PixelBlueGreenRedReserved8BitPerColor:
            cb_fb->bits_per_pixel = 32;
            cb_fb->blue_mask_pos = 0;
            cb_fb->blue_mask_size = 8;
            cb_fb->green_mask_pos = 8;
            cb_fb->green_mask_size = 8;
            cb_fb->red_mask_pos = 16;
            cb_fb->red_mask_size = 8;
            cb_fb->reserved_mask_pos = 24;
            cb_fb->reserved_mask_size = 8;
            break;
        case PixelBitMask:
            /* Reject modes with all-zero pixel masks */
            if ((info->PixelInformation.RedMask
               | info->PixelInformation.GreenMask
               | info->PixelInformation.BlueMask
               | info->PixelInformation.ReservedMask) == 0) {
                printf("PixelBitMask mode with all-zero masks\n");
                return EFI_UNSUPPORTED;
            }

            /* Calculate BPP from masks instead of assuming 32 */
            cb_fb->bits_per_pixel = linear_masks_to_bpp(
                info->PixelInformation.RedMask,
                info->PixelInformation.GreenMask,
                info->PixelInformation.BlueMask,
                info->PixelInformation.ReservedMask);

            // Calculate position (find first set bit, 0 if mask is empty)
            cb_fb->red_mask_pos = info->PixelInformation.RedMask ? __builtin_ffs(info->PixelInformation.RedMask) - 1 : 0;
            cb_fb->green_mask_pos = info->PixelInformation.GreenMask ? __builtin_ffs(info->PixelInformation.GreenMask) - 1 : 0;
            cb_fb->blue_mask_pos = info->PixelInformation.BlueMask ? __builtin_ffs(info->PixelInformation.BlueMask) - 1 : 0;
            cb_fb->reserved_mask_pos = info->PixelInformation.ReservedMask ? __builtin_ffs(info->PixelInformation.ReservedMask) - 1 : 0;

            // Calculate size (count set bits)
            cb_fb->red_mask_size = __builtin_popcount(info->PixelInformation.RedMask);
            cb_fb->green_mask_size = __builtin_popcount(info->PixelInformation.GreenMask);
            cb_fb->blue_mask_size = __builtin_popcount(info->PixelInformation.BlueMask);
            cb_fb->reserved_mask_size = __builtin_popcount(info->PixelInformation.ReservedMask);
            break;
        default:
            printf("Unsupported pixel format: %d\n", info->PixelFormat);
            return EFI_UNSUPPORTED;
    }

    /*
     * Recalculate pitch from gop->Mode->Info, as some firmware (e.g. Apple
     * Macs) report incorrect PixelsPerScanLine via QueryMode.
     */
    cb_fb->bytes_per_line = gop->Mode->Info->PixelsPerScanLine * (cb_fb->bits_per_pixel / 8);

    /* Validate pitch */
    {
        uint32_t bytes_per_pixel = cb_fb->bits_per_pixel / 8;
        if (bytes_per_pixel == 0
         || cb_fb->bytes_per_line % bytes_per_pixel != 0
         || cb_fb->bytes_per_line < cb_fb->x_resolution * bytes_per_pixel) {
            printf("Invalid pitch %u (width=%u, bpp=%u)\n",
                   cb_fb->bytes_per_line, cb_fb->x_resolution, cb_fb->bits_per_pixel);
            return EFI_UNSUPPORTED;
        }
    }

    vbios_loc = vgabios_bin;
    vbios_size = sizeof(vgabios_bin);

    priv->video_type = CSMWRAP_VIDEO_SEAVGABIOS;

    printf("Video Initialisation Succeed with SeaVGABIOS GOP\n");

    return 0;

}

EFI_STATUS csmwrap_video_prepare_exitbs(struct csmwrap_priv *priv)
{
    /*
     * Unlink Controller before ExitBS, it mat disable FB so we can't
     * do that for other video types.
     */
    if (priv->video_type == CSMWRAP_VIDEO_OPROM) {
        EFI_STATUS Status;

        if (!priv->gop_handle) {
            DEBUG((DEBUG_ERROR, "No GOP handle found\n"));
            return EFI_UNSUPPORTED;
        }

        if (gBS->Hdr.Revision < EFI_1_10_BOOT_SERVICES_REVISION && !gBS->DisconnectController) {
            DEBUG((DEBUG_ERROR, "DisconnectController not supported\n"));
            return EFI_UNSUPPORTED;
        }

        Status = gBS->DisconnectController(
                        priv->gop_handle,
                        NULL,
                        NULL
                        );

        if (EFI_ERROR(Status)) {
            DEBUG((DEBUG_ERROR, "DisconnectController failed: %d\n", Status));
            return Status;
        }
    }

    return EFI_SUCCESS;
}

void csmwrap_video_early_init(struct csmwrap_priv *priv) {
    if (FindGop(priv) != EFI_SUCCESS) {
        priv->cb_fb.physical_address = 0;
        return;
    }

    if (csmwrap_video_seavgabios_init(priv) != EFI_SUCCESS) {
        priv->cb_fb.physical_address = 0;
        return;
    }

    /* Clear vbios_loc so csmwrap_video_init() doesn't skip OpROM init */
    vbios_loc = NULL;
}

/*
 * If a specific VGA device is configured, find its GOP handle and switch
 * priv->gop_handle so that DisconnectController targets the correct device
 * during exit-boot-services preparation.
 */
static void FindVgaGop(struct csmwrap_priv *priv)
{
    EFI_HANDLE *HandleBuffer;
    UINTN HandleCount;
    EFI_GUID gopGuid = EFI_GRAPHICS_OUTPUT_PROTOCOL_GUID;
    EFI_GUID DevicePathGuid = EFI_DEVICE_PATH_PROTOCOL_GUID;
    EFI_GUID PciIoGuid = EFI_PCI_IO_PROTOCOL_GUID;

    if (gBS->LocateHandleBuffer(ByProtocol, &gopGuid, NULL,
                                 &HandleCount, &HandleBuffer))
        return;

    for (UINTN i = 0; i < HandleCount; i++) {
        EFI_DEVICE_PATH_PROTOCOL *DevicePath;
        if (gBS->HandleProtocol(HandleBuffer[i], &DevicePathGuid,
                                 (VOID **)&DevicePath))
            continue;

        EFI_HANDLE PciHandle;
        if (gBS->LocateDevicePath(&PciIoGuid, &DevicePath, &PciHandle))
            continue;

        EFI_PCI_IO_PROTOCOL *PciIo;
        if (gBS->HandleProtocol(PciHandle, &PciIoGuid, (VOID **)&PciIo))
            continue;

        UINTN Seg, Bus, Device, Function;
        PciIo->GetLocation(PciIo, &Seg, &Bus, &Device, &Function);

        if ((uint8_t)Bus != gConfig.vga_bus ||
            (uint8_t)Device != gConfig.vga_device ||
            (uint8_t)Function != gConfig.vga_function)
            continue;

        EFI_GRAPHICS_OUTPUT_PROTOCOL *Gop;
        if (gBS->HandleProtocol(HandleBuffer[i], &gopGuid, (VOID **)&Gop))
            continue;

        priv->gop = Gop;
        priv->gop_handle = HandleBuffer[i];
        printf("VGA: switched GOP to configured device %02x:%02x.%x\n",
               gConfig.vga_bus, gConfig.vga_device, gConfig.vga_function);
        break;
    }

    gBS->FreePool(HandleBuffer);
}

EFI_STATUS csmwrap_video_init(struct csmwrap_priv *priv)
{
    EFI_STATUS status;

    /* Find GOP if not already found by early init */
    if (!priv->gop) {
        status = FindGop(priv);
        if (EFI_ERROR(status)) {
            printf("Unable to get GOP service\n");
            return -1;
        }
    }

    if (vbios_loc != NULL) {
        /*
         * User-provided VBIOS: still need PCI info and VGA arbitration
         * so the VBIOS is dispatched to the right device.
         */
        FindVgaPciInfo(priv);
        status = csmwrap_pci_vgaarb(priv);
        if (status != EFI_SUCCESS) {
            printf("VGA arbitration failed, cannot dispatch user VBIOS\n");
            vbios_loc = NULL;
            vbios_size = 0;
            /* Fall through to try SeaVGABIOS instead */
            goto try_seavga;
        }
        if (gConfig.vga_specified)
            FindVgaGop(priv);
        priv->video_type = CSMWRAP_VIDEO_OPROM;
        return 0;
    }

    /* Try OpROM first (will fail if no PCI info or AMD RDNA+) */
    status = csmwrap_video_oprom_init(priv);
    if (status == EFI_SUCCESS) {
        /*
         * Switch gop_handle to the VGA device so DisconnectController
         * targets the right device during exit-boot-services preparation.
         */
        if (gConfig.vga_specified) {
            FindVgaGop(priv);
        }
        return 0;
    }

    if (gConfig.vga_specified) {
        printf("VGA: configured device %02x:%02x.%x has no usable OpROM, ignoring\n",
               gConfig.vga_bus, gConfig.vga_device, gConfig.vga_function);
    }

try_seavga:
    status = csmwrap_video_seavgabios_init(priv);
    if (status == EFI_SUCCESS) {
        return 0;
    }

    printf("FATAL: No video initialization method available!\n");
    printf("       Neither OpROM nor SeaVGABIOS could be initialized.\n");
    for (;;)
        asm volatile ("hlt");
}

